import test from "node:test";
import assert from "node:assert/strict";
import { AgentBudget, AgentDecision, AgentMode, AgentPolicy, AgentStatus, SeoAgentOrchestrator, SeoAgentPlanner, ToolRegistry, createSeoGrowToolRegistry } from "./agentRuntime.js";

const tool = (name, execute, extra = {}) => ({ name, description: name, inputSchema: {}, outputSchema: {}, source: "LOCAL_DATA", cost: "NONE", freshnessMs: 0, risk: "LOW", permission: "READ", mutatesData: false, timeoutMs: 100, execute, ...extra });
test("il planner seleziona i cinque workflow SEO", () => { const planner = new SeoAgentPlanner(); assert.equal(planner.plan("opportunità SEO").workflow, "TOP_OPPORTUNITIES"); assert.equal(planner.plan("calo traffico").workflow, "TRAFFIC_DROP"); assert.equal(planner.plan("pagine Top 10").workflow, "TOP_10_PUSH"); assert.equal(planner.plan("contenuti da aggiornare").workflow, "CONTENT_DECAY"); assert.equal(planner.plan("internal linking").workflow, "INTERNAL_LINKING"); });
test("la registry blocca duplicati semanticamente equivalenti", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("read", () => { calls += 1; return [1]; })); const context = { runId: "r", projectId: 1, dataVersion: "v", budget: new AgentBudget(), policy: new AgentPolicy() }; await registry.execute("read", { b: 2, a: 1 }, context); const repeated = await registry.execute("read", { a: 1, b: 2 }, context); assert.equal(calls, 1); assert.equal(repeated.reused, true); });
test("la cache cambia insieme alla versione dati", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("read", () => { calls += 1; return []; }, { freshnessMs: 60_000 })); const base = { projectId: 1, budget: new AgentBudget(), policy: new AgentPolicy() }; await registry.execute("read", {}, { ...base, runId: "a", dataVersion: "1" }); await registry.execute("read", {}, { ...base, runId: "b", dataVersion: "2" }); assert.equal(calls, 2); });
test("il loop ritenta un errore transitorio", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("data.gsc", () => { calls += 1; if (calls === 1) throw new Error("temporaneo"); return { queries: [{ dimension: "seo", impressions: 100, position: 8 }] }; })); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ id: "s", tool: "data.gsc", input: {}, status: "PENDING" }] }), replan: () => {} }; const run = await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxRetries: 1 } }); assert.equal(calls, 2); assert.equal(run.budget.used.retries, 1); });
test("il replanning sostituisce il piano e continua", async () => { const calls = []; const registry = new ToolRegistry().register(tool("one", () => calls.push("one"))).register(tool("two", () => calls.push("two"))); const planner = { plan: () => ({ version: 1, workflow: "TOP_OPPORTUNITIES", steps: [{ id: "1", tool: "one", input: {} }] }), replan: (plan, steps) => ({ ...plan, version: 2, steps: steps.map((step) => ({ id: "2", input: {}, ...step })) }) }; let first = true; const assessor = () => first ? (first = false, { decision: AgentDecision.REPLAN, steps: [{ tool: "two" }] }) : { decision: AgentDecision.COMPLETE }; await new SeoAgentOrchestrator({ registry, planner, assessor }).run("goal", { projectId: 1 }); assert.deepEqual(calls, ["one", "two"]); });
test("il limite step conserva un risultato parziale", async () => { const registry = new ToolRegistry().register(tool("one", () => [1])).register(tool("two", () => [2])); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "one", input: {} }, { tool: "two", input: {} }] }), replan: () => {} }; const run = await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxSteps: 1 } }); assert.equal(run.status, AgentStatus.PARTIAL); assert.match(run.errors.join(" "), /BUDGET_EXCEEDED/); });
test("le policy proteggono write e categorie ad alto rischio", () => { const write = { mutatesData: true, risk: "LOW", category: "content" }, canonical = { mutatesData: true, risk: "HIGH", category: "canonical" }; assert.equal(new AgentPolicy(AgentMode.READ_ONLY).check(write).allowed, false); assert.equal(new AgentPolicy(AgentMode.ASSISTED).check(write).approvalRequired, true); assert.equal(new AgentPolicy(AgentMode.AUTONOMOUS).check(write).allowed, true); assert.equal(new AgentPolicy(AgentMode.AUTONOMOUS).check(canonical).approvalRequired, true); });
test("un timeout diventa osservazione fallita controllata", async () => { const registry = new ToolRegistry().register(tool("slow", () => new Promise((resolve) => setTimeout(resolve, 50)), { timeoutMs: 5 })); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "slow", input: {} }] }), replan: () => {} }; const run = await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxRetries: 0 } }); assert.equal(run.observations[0].status, "FAILED"); assert.notEqual(run.status, AgentStatus.COMPLETED); });
test("senza dati reali il risultato è BLOCKED", async () => { const run = await new SeoAgentOrchestrator({ registry: createSeoGrowToolRegistry() }).run("opportunità", { projectId: 1 }); assert.equal(run.status, AgentStatus.BLOCKED); assert.match(run.errors.join(" "), /insufficienti/); });
test("il workflow base riusa le opportunità 1.4.2 e produce evidenza", async () => { const dataset = { importedAt: "2026-09-01", queries: [{ dimension: "seo agent", page: "https://example.com/seo", clicks: 8, impressions: 800, ctr: 1, position: 11.2 }] }; const run = await new SeoAgentOrchestrator({ registry: createSeoGrowToolRegistry() }).run("Trova opportunità SEO", { projectId: 1, dataset, dataVersion: dataset.importedAt }); assert.equal(run.status, AgentStatus.COMPLETED); assert.equal(run.recommendations.length, 1); assert.deepEqual(run.recommendations[0].sources, ["Google Search Console"]); });
