import test from "node:test";
import assert from "node:assert/strict";
import { AgentBudget, AgentDecision, AgentError, AgentMode, AgentPolicy, AgentStatus, SeoAgentOrchestrator, SeoAgentPlanner, ToolRegistry, createSeoGrowToolRegistry } from "./agentRuntime.js";

const tool = (name, execute, extra = {}) => ({ name, description: name, inputSchema: {}, outputSchema: {}, source: "LOCAL_DATA", cost: "NONE", freshnessMs: 0, risk: "LOW", permission: "READ", mutatesData: false, timeoutMs: 100, idempotent: true, supportsAbort: true, execute, ...extra });
test("il planner seleziona i cinque workflow SEO", () => { const planner = new SeoAgentPlanner(); assert.equal(planner.plan("opportunità SEO").workflow, "TOP_OPPORTUNITIES"); assert.equal(planner.plan("calo traffico").workflow, "TRAFFIC_DROP"); assert.equal(planner.plan("pagine Top 10").workflow, "TOP_10_PUSH"); assert.equal(planner.plan("contenuti da aggiornare").workflow, "CONTENT_DECAY"); assert.equal(planner.plan("internal linking").workflow, "INTERNAL_LINKING"); });
test("la registry blocca duplicati semanticamente equivalenti", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("read", () => { calls += 1; return [1]; })); const context = { runId: "r", projectId: 1, dataVersion: "v", budget: new AgentBudget(), policy: new AgentPolicy() }; await registry.execute("read", { b: 2, a: 1 }, context); const repeated = await registry.execute("read", { a: 1, b: 2 }, context); assert.equal(calls, 1); assert.equal(repeated.reused, true); });
test("la cache cambia insieme alla versione dati", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("read", () => { calls += 1; return []; }, { freshnessMs: 60_000 })); const base = { projectId: 1, budget: new AgentBudget(), policy: new AgentPolicy() }; await registry.execute("read", {}, { ...base, runId: "a", dataVersion: "1" }); await registry.execute("read", {}, { ...base, runId: "b", dataVersion: "2" }); assert.equal(calls, 2); });
test("il loop ritenta un errore transitorio", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("data.gsc", () => { calls += 1; if (calls === 1) throw new AgentError("NETWORK_ERROR", "temporaneo"); return { queries: [{ dimension: "seo", impressions: 100, position: 8 }] }; })); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ id: "s", tool: "data.gsc", input: {}, status: "PENDING" }] }), replan: () => {} }; const run = await new SeoAgentOrchestrator({ registry, planner, sleep: async () => {} }).run("goal", { projectId: 1, budget: { maxRetries: 1 } }); assert.equal(calls, 2); assert.equal(run.budget.used.retries, 1); });
test("il replanning sostituisce il piano e continua", async () => { const calls = []; const registry = new ToolRegistry().register(tool("one", () => calls.push("one"))).register(tool("two", () => calls.push("two"))); const planner = { plan: () => ({ version: 1, workflow: "TOP_OPPORTUNITIES", steps: [{ id: "1", tool: "one", input: {} }] }), replan: (plan, steps) => ({ ...plan, version: 2, steps: steps.map((step) => ({ id: "2", input: {}, ...step })) }) }; let first = true; const assessor = () => first ? (first = false, { decision: AgentDecision.REPLAN, steps: [{ tool: "two" }] }) : { decision: AgentDecision.COMPLETE }; await new SeoAgentOrchestrator({ registry, planner, assessor }).run("goal", { projectId: 1 }); assert.deepEqual(calls, ["one", "two"]); });
test("il limite step conserva un risultato parziale", async () => { const registry = new ToolRegistry().register(tool("one", () => [1])).register(tool("two", () => [2])); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "one", input: {} }, { tool: "two", input: {} }] }), replan: () => {} }; const run = await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxSteps: 1 } }); assert.equal(run.status, AgentStatus.PARTIAL); assert.match(run.errors.join(" "), /BUDGET_EXCEEDED/); });
test("le policy proteggono write e categorie ad alto rischio", () => { const write = { mutatesData: true, risk: "LOW", category: "content" }, canonical = { mutatesData: true, risk: "HIGH", category: "canonical" }; assert.equal(new AgentPolicy(AgentMode.READ_ONLY).check(write).allowed, false); assert.equal(new AgentPolicy(AgentMode.ASSISTED).check(write).approvalRequired, true); assert.equal(new AgentPolicy(AgentMode.AUTONOMOUS).check(write).allowed, true); assert.equal(new AgentPolicy(AgentMode.AUTONOMOUS).check(canonical).approvalRequired, true); });
test("un timeout diventa osservazione fallita controllata", async () => { const registry = new ToolRegistry().register(tool("slow", () => new Promise((resolve) => setTimeout(resolve, 50)), { timeoutMs: 5 })); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "slow", input: {} }] }), replan: () => {} }; const run = await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxRetries: 0 } }); assert.equal(run.observations[0].status, "FAILED"); assert.notEqual(run.status, AgentStatus.COMPLETED); });
test("senza dati reali il risultato è BLOCKED", async () => { const run = await new SeoAgentOrchestrator({ registry: createSeoGrowToolRegistry() }).run("opportunità", { projectId: 1 }); assert.equal(run.status, AgentStatus.BLOCKED); assert.match(run.errors.join(" "), /insufficienti/); });
test("il workflow base riusa le opportunità 1.4.2 e produce evidenza", async () => { const dataset = { importedAt: "2026-09-01", queries: [{ dimension: "seo agent", page: "https://example.com/seo", clicks: 8, impressions: 800, ctr: 1, position: 11.2 }] }; const run = await new SeoAgentOrchestrator({ registry: createSeoGrowToolRegistry() }).run("Trova opportunità SEO", { projectId: 1, dataset, dataVersion: dataset.importedAt }); assert.equal(run.status, AgentStatus.COMPLETED); assert.equal(run.recommendations.length, 1); assert.deepEqual(run.recommendations[0].sources, ["Google Search Console"]); });
test("un errore permanente non viene ritentato", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("bad", () => { calls += 1; throw new AgentError("SCHEMA_INVALID", "input errato"); })); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "bad", input: {} }] }), replan: () => {} }; await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxRetries: 3 } }); assert.equal(calls, 1); });
test("input e output sono validati realmente", async () => { const registry = new ToolRegistry().register(tool("schema", () => ({}), { inputSchema: { type: "object", required: ["url"], properties: { url: { type: "string" } } }, outputSchema: { type: "object", required: ["ok"], properties: { ok: { type: "boolean" } } } })); const context = { runId: "schema", projectId: 1, dataVersion: "", budget: new AgentBudget(), policy: new AgentPolicy() }; await assert.rejects(() => registry.execute("schema", {}, context), (error) => error.code === "SCHEMA_INVALID"); await assert.rejects(() => registry.execute("schema", { url: "https://example.com" }, context), (error) => error.code === "SCHEMA_INVALID"); });
test("un obiettivo sconosciuto viene rifiutato e il limite risultati è rispettato", async () => { const planner = new SeoAgentPlanner(); assert.throws(() => planner.plan("fammi qualcosa"), (error) => error.code === "UNSUPPORTED_GOAL"); const plan = planner.plan("Dammi le 3 migliori opportunità"); assert.equal(plan.parameters.maxResults, 3); const dataset = { queries: Array.from({ length: 8 }, (_, index) => ({ dimension: `query ${index}`, impressions: 100 + index, clicks: 1, ctr: 1, position: 8 })) }; const run = await new SeoAgentOrchestrator({ registry: createSeoGrowToolRegistry() }).run("Dammi le 3 migliori opportunità", { projectId: 1, dataset }); assert.equal(run.recommendations.length, 3); });
test("il ciclo di replanning viene interrotto", async () => { const registry = new ToolRegistry().register(tool("one", () => [1])); const planner = { plan: () => ({ version: 1, workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "one", input: {} }] }), replan: (plan) => ({ ...plan, version: plan.version + 1, steps: [{ tool: "one", input: {} }] }) }; const run = await new SeoAgentOrchestrator({ registry, planner, assessor: () => ({ decision: AgentDecision.REPLAN, steps: [{ tool: "one" }] }) }).run("goal", { projectId: 1 }); assert.equal(run.status, AgentStatus.BLOCKED); assert.match(run.errors.join(" "), /Ciclo/); });
test("max replans e cache non aggirano i budget", async () => { const registry = new ToolRegistry().register(tool("one", () => [1], { freshnessMs: 60_000 })); const planner = { plan: () => ({ version: 1, workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "one", input: {} }] }), replan: (plan, steps) => ({ ...plan, version: plan.version + 1, steps }) }; const orchestrator = new SeoAgentOrchestrator({ registry, planner, assessor: () => ({ decision: AgentDecision.REPLAN, steps: [{ tool: "one", input: { n: Math.random() } }] }) }); const run = await orchestrator.run("goal", { projectId: 1, budget: { maxReplans: 1, maxSteps: 2 } }); assert.equal(run.status, AgentStatus.PARTIAL); assert.ok(run.budget.used.steps <= 2); });
test("timeout e cancellazione abortiscono davvero il tool", async () => { let aborted = false, runId; const registry = new ToolRegistry().register(tool("slow", (_input, { signal }) => new Promise((resolve, reject) => signal.addEventListener("abort", () => { aborted = true; reject(signal.reason); }, { once: true })), { timeoutMs: 200 })); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ tool: "slow", input: {} }] }), replan: () => {} }; const orchestrator = new SeoAgentOrchestrator({ registry, planner, onUpdate: (run) => { runId ||= run.id; } }); const pending = orchestrator.run("goal", { projectId: 1 }); await new Promise((resolve) => setTimeout(resolve, 5)); orchestrator.cancel(runId); const run = await pending; assert.equal(aborted, true); assert.equal(run.status, AgentStatus.CANCELLED); });
test("approvazione e rifiuto usano token monouso e high-risk resta bloccato", async () => { let writes = 0; const write = tool("write", () => { writes += 1; return { ok: true }; }, { mutatesData: true, permission: "WRITE", risk: "HIGH", category: "canonical", idempotent: false, preview: async () => ({ current: "a", proposed: "b" }) }); const planner = { plan: () => ({ workflow: "TOP_OPPORTUNITIES", steps: [{ id: "w", tool: "write", input: {} }] }), replan: () => {} }; const orchestrator = new SeoAgentOrchestrator({ registry: new ToolRegistry().register(write), planner }); const waiting = await orchestrator.run("goal", { projectId: 1, mode: AgentMode.AUTONOMOUS }); assert.equal(waiting.status, AgentStatus.WAITING_APPROVAL); const rejected = await orchestrator.resolveApproval(waiting, { projectId: 1 }, { approved: false, token: waiting.pendingApproval.token }); assert.equal(rejected.status, AgentStatus.BLOCKED); assert.equal(writes, 0); await assert.rejects(() => orchestrator.resolveApproval(waiting, { projectId: 1 }, { approved: true, token: waiting.pendingApproval.token }), /già utilizzato/); });
test("Top 10 usa realmente il formato ranking dell’app", async () => { const dataset = { queries: [{ dimension: "seo agent", impressions: 500, clicks: 4, ctr: 1, position: 8 }] }; const rankings = [{ checkedAt: "2026-09-04", rankings: [{ keyword: "seo agent", position: 14 }] }]; const run = await new SeoAgentOrchestrator({ registry: createSeoGrowToolRegistry() }).run("pagine Top 10", { projectId: 1, dataset, rankings }); assert.equal(run.recommendations[0].evidence.find((item) => item.metric === "position").value, 14); assert.ok(run.recommendations[0].sources.includes("DataForSEO")); });
test("runCalls e in-flight vengono ripuliti a fine run", async () => { const registry = createSeoGrowToolRegistry(); await new SeoAgentOrchestrator({ registry }).run("opportunità", { projectId: 1 }); assert.equal(registry.runCalls.size, 0); assert.equal(registry.inFlight.size, 0); });
test("dopo approval il piano riprende dallo step successivo senza doppio addebito", async () => { const calls = []; const registry = new ToolRegistry().register(tool("read.one", () => (calls.push("one"), [1]))).register(tool("write", () => (calls.push("write"), { ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false })).register(tool("read.two", () => (calls.push("two"), [2]))); const planner = { plan: () => ({ workflow: "CUSTOM", parameters: {}, steps: [{ id: "1", tool: "read.one", input: {}, required: true }, { id: "2", tool: "write", input: {}, required: true }, { id: "3", tool: "read.two", input: {}, required: true }] }), replan: () => {} }; const orchestrator = new SeoAgentOrchestrator({ registry, planner }); const waiting = await orchestrator.run("goal", { projectId: 1, budget: { maxSteps: 3 } }); const done = await orchestrator.resolveApproval(waiting, { projectId: 1 }, { approved: true, token: waiting.pendingApproval.token }); assert.deepEqual(calls, ["one", "write", "two"]); assert.notEqual(done.plan.steps[2].status, "PENDING"); assert.equal(done.budget.used.steps, 3); });
test("approval è vincolata al progetto e sopravvive a una nuova istanza", async () => { let writes = 0; const registry = new ToolRegistry().register(tool("write.bound", () => (writes += 1, { ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false })); const planner = { plan: () => ({ workflow: "CUSTOM", steps: [{ id: "w", tool: "write.bound", input: {}, required: true }] }), replan: () => {} }; const first = new SeoAgentOrchestrator({ registry, planner }); const waiting = await first.run("goal", { projectId: 1 }); await assert.rejects(() => first.resolveApproval(waiting, { projectId: 2 }, { approved: true, token: waiting.pendingApproval.token }), (error) => error.code === "APPROVAL_CONTEXT_MISMATCH"); const second = new SeoAgentOrchestrator({ registry, planner }); await second.resolveApproval(waiting, { projectId: 1 }, { approved: true, token: waiting.pendingApproval.token }); const third = new SeoAgentOrchestrator({ registry, planner }); await assert.rejects(() => third.resolveApproval(waiting, { projectId: 1 }, { approved: true, token: waiting.pendingApproval.token }), /già utilizzato/); assert.equal(writes, 1); });
test("preview lenta rispetta timeout e abort", async () => { let previewAborted = false; const registry = new ToolRegistry().register(tool("write.preview", () => ({ ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false, timeoutMs: 10, preview: (_input, { signal }) => new Promise((resolve, reject) => signal.addEventListener("abort", () => { previewAborted = true; reject(signal.reason); }, { once: true })) })); const planner = { plan: () => ({ workflow: "CUSTOM", steps: [{ tool: "write.preview", input: {}, required: true }] }), replan: () => {} }; const run = await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxDurationMs: 20 } }); assert.equal(previewAborted, true); assert.equal(run.status, AgentStatus.PARTIAL); });
test("fallimento required rende il risultato PARTIAL", async () => { const registry = new ToolRegistry().register(tool("data.gsc", () => ({ queries: [{ dimension: "seo", impressions: 100, clicks: 1, ctr: 1, position: 12 }] }))).register(tool("seo.opportunities", () => [{ dimension: "seo", impressions: 100, clicks: 1, ctr: 1, position: 12 }])).register(tool("data.rankings", () => { throw new AgentError("SCHEMA_INVALID", "ranking invalido"); })); const plan = { workflow: "TOP_10_PUSH", parameters: {}, steps: ["data.gsc", "seo.opportunities", "data.rankings"].map((name) => ({ tool: name, input: {}, required: true })) }; const run = await new SeoAgentOrchestrator({ registry, planner: { plan: () => plan, replan: () => {} } }).run("goal", { projectId: 1 }); assert.equal(run.status, AgentStatus.PARTIAL); assert.ok(run.recommendations.length); });
test("cache usable alimenta raccomandazioni e in-flight provider consuma una quota", async () => { let calls = 0; const registry = new ToolRegistry().register(tool("data.gsc", () => ({ queries: [{ dimension: "seo", impressions: 100, clicks: 1, ctr: 1, position: 12 }] }), { freshnessMs: 60_000 })).register(tool("data.analysis", () => null, { freshnessMs: 60_000 })).register(tool("seo.opportunities", () => [{ dimension: "seo", impressions: 100, clicks: 1, ctr: 1, position: 12 }], { freshnessMs: 60_000 })); const orchestrator = new SeoAgentOrchestrator({ registry }); await orchestrator.run("opportunità", { projectId: 1, dataVersion: "v1" }); const second = await orchestrator.run("opportunità", { projectId: 1, dataVersion: "v1" }); assert.equal(second.status, AgentStatus.COMPLETED); assert.ok(second.observations.some((item) => item.status === "CACHED")); const paid = new ToolRegistry().register(tool("paid", async () => { calls += 1; await new Promise((resolve) => setTimeout(resolve, 5)); return [1]; }, { source: "DATAFORSEO", freshnessMs: 0 })); const context = { runId: "same", projectId: 1, dataVersion: "v", budget: new AgentBudget({ maxDataForSeoCalls: 1 }), policy: new AgentPolicy(), signal: new AbortController().signal }; const results = await Promise.all([paid.execute("paid", {}, context), paid.execute("paid", {}, context)]); assert.equal(results.length, 2); assert.equal(calls, 1); });
test("costo stimato è bloccato prima dell’esecuzione", async () => { let called = false; const registry = new ToolRegistry().register(tool("paid.cost", () => (called = true, { cost: 2.5 }), { estimatedCost: 2.5 })); const context = { runId: "cost", projectId: 1, dataVersion: "", budget: new AgentBudget({ maxCost: 0 }), policy: new AgentPolicy(), signal: new AbortController().signal }; await assert.rejects(() => registry.execute("paid.cost", {}, context), /cost/); assert.equal(called, false); });

test("due step high-risk consecutivi richiedono due approvazioni distinte", async () => {
  let writes = 0;
  const registry = new ToolRegistry()
    .register(tool("write.one", () => (writes += 1, { ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false }))
    .register(tool("write.two", () => (writes += 1, { ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false }));
  const planner = { plan: () => ({ workflow: "CUSTOM", steps: [{ id: "1", tool: "write.one", input: {}, required: true }, { id: "2", tool: "write.two", input: {}, required: true }] }), replan: () => {} };
  const orchestrator = new SeoAgentOrchestrator({ registry, planner });
  const first = await orchestrator.run("goal", { projectId: 1, budget: { maxSteps: 2 } });
  const second = await orchestrator.resolveApproval(first, { projectId: 1 }, { approved: true, token: first.pendingApproval.token });
  assert.equal(second.status, AgentStatus.WAITING_APPROVAL); assert.equal(second.pendingApproval.stepIndex, 1); assert.notEqual(second.pendingApproval.token, first.pendingApproval.token); assert.equal(writes, 1);
  const done = await orchestrator.resolveApproval(second, { projectId: 1 }, { approved: true, token: second.pendingApproval.token });
  assert.equal(writes, 2); assert.equal(done.plan.steps[1].status, "COMPLETED");
});

test("retry e assessment restano attivi dopo una approvazione", async () => {
  let reads = 0, assessments = 0;
  const registry = new ToolRegistry()
    .register(tool("write", () => ({ ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false }))
    .register(tool("read", () => { reads += 1; if (reads === 1) throw new AgentError("NETWORK_ERROR", "temporaneo"); return [1]; }));
  const planner = { plan: () => ({ workflow: "CUSTOM", steps: [{ id: "1", tool: "write", input: {} }, { id: "2", tool: "read", input: {} }] }), replan: () => {} };
  const orchestrator = new SeoAgentOrchestrator({ registry, planner, assessor: () => (assessments += 1, { decision: AgentDecision.CONTINUE }), sleep: async () => {} });
  const waiting = await orchestrator.run("goal", { projectId: 1, budget: { maxSteps: 2, maxRetries: 1 } });
  const done = await orchestrator.resolveApproval(waiting, { projectId: 1 }, { approved: true, token: waiting.pendingApproval.token });
  assert.equal(reads, 2); assert.equal(done.budget.used.retries, 1); assert.equal(assessments, 2);
});

test("replanning resta attivo dopo una approvazione", async () => {
  const calls = [];
  const registry = new ToolRegistry()
    .register(tool("write", () => (calls.push("write"), { ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false }))
    .register(tool("read", () => (calls.push("read"), [1])));
  const planner = { plan: () => ({ version: 1, workflow: "CUSTOM", steps: [{ id: "1", tool: "write", input: {} }] }), replan: (plan) => ({ ...plan, version: 2, steps: [{ id: "2", tool: "read", input: {} }] }) };
  let firstAssessment = true;
  const assessor = () => firstAssessment ? (firstAssessment = false, { decision: AgentDecision.REPLAN, steps: [{ tool: "read" }] }) : { decision: AgentDecision.COMPLETE };
  const orchestrator = new SeoAgentOrchestrator({ registry, planner, assessor });
  const waiting = await orchestrator.run("goal", { projectId: 1, budget: { maxSteps: 2 } });
  const done = await orchestrator.resolveApproval(waiting, { projectId: 1 }, { approved: true, token: waiting.pendingApproval.token });
  assert.deepEqual(calls, ["write", "read"]); assert.equal(done.plan.version, 2); assert.equal(done.budget.used.replans, 1);
});

test("un costo effettivo oltre il budget interrompe gli step successivi", async () => {
  let laterCalls = 0, receivedLimit;
  const registry = new ToolRegistry()
    .register(tool("paid", (_input, context) => { receivedLimit = context.providerCostLimit; return { ok: true, cost: 1 }; }, { estimatedCost: 0.1 }))
    .register(tool("later", () => (laterCalls += 1, [1])));
  const planner = { plan: () => ({ workflow: "CUSTOM", steps: [{ tool: "paid", input: {}, required: true }, { tool: "later", input: {} }] }), replan: () => {} };
  const run = await new SeoAgentOrchestrator({ registry, planner }).run("goal", { projectId: 1, budget: { maxCost: 0.1, maxSteps: 2 } });
  assert.equal(run.status, AgentStatus.PARTIAL); assert.equal(laterCalls, 0); assert.equal(receivedLimit, 0.1); assert.equal(run.budget.used.cost, 1); assert.equal(run.budget.used.costOverrun, 0.9); assert.match(run.errors.join(" "), /superato il budget/);
});

test("una scadenza approvazione mancante o non valida viene rifiutata", async () => {
  const registry = new ToolRegistry().register(tool("write.expiry", () => ({ ok: true }), { mutatesData: true, permission: "WRITE", risk: "HIGH", idempotent: false }));
  const planner = { plan: () => ({ workflow: "CUSTOM", steps: [{ id: "w", tool: "write.expiry", input: {} }] }), replan: () => {} };
  const orchestrator = new SeoAgentOrchestrator({ registry, planner });
  const waiting = await orchestrator.run("goal", { projectId: 1 }); waiting.pendingApproval.expiresAt = "not-a-date";
  await assert.rejects(() => orchestrator.resolveApproval(waiting, { projectId: 1 }, { approved: true, token: waiting.pendingApproval.token }), (error) => error.code === "APPROVAL_INVALID");
});
